server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://121.42.14.67:3306/db_study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: lixc0426
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-not-delete-value: N
      logic-delete-value: Y
      logic-delete-field: deleted

logging:
  level:
    com.xc.justforjoy: debug